

#define PIZZA_TIMER_DEFAULT_TIME 300


#define MENU_STATE_INACTIVE				0
#define MENU_STATE_PIZZA1					1
#define MENU_STATE_PIZZA2					2
#define MENU_STATE_PIZZA3					3
#define MENU_STATE_SELECT_TIME		4
#define MENU_STATE_SELECT_REPAINT 5

