#ifndef MENU_DEFS_H_
#define MENU_DEFS_H_

#define MENU_TIMEOUT_SECONDS		          30
#define MENU_TIMEOUT_SELECT_SECONDS	      15
#define PIZZA_TIMER_DEFAULT_TIME         300

enum menu_state {
	MENU_STATE_INACTIVE = 0,
	MENU_STATE_PIZZA1,
	MENU_STATE_PIZZA2,
	MENU_STATE_PIZZA3,
	MENU_STATE_SELECT_TIME,
	MENU_STATE_SELECT_REPAINT,
	MENU_STATE_APPLY_TIMER,
};

#endif /* MENU_DEFS_H_ */
